### ISSUE TITLE
[JAVA] : SingleNumber

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#19]
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only constant extra space.

Example 1:

Input: nums = [2,2,1]
Output: 1
Example 2:

Input: nums = [4,1,2,1,2]
Output: 4
Example 3:

Input: nums = [1]
Output: 1

Implementation for this problem is required for Java. The boilerplate code can be found in `java/array/SingleNumber.java`

**Comment by rohitsinghind** [comment]
Hello sir, Can you assign this issue to me?

**Comment by ShubhKotnala** [comment]
Sure @rohitsinghind , please go ahead and raise a PR whenever you are ready. 
Thanks for the contribution!

**Comment by rohitsinghind** [comment]
done

**Comment by ShubhKotnala** [comment]
Closing this issue w.r.t https://github.com/ShubhKotnala/Data_Structures_And_Algorithms/pull/36
