### ISSUE TITLE
[JavaScript]: SingleNumber

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#20]
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only constant extra space.

Example 1:

Input: nums = [2,2,1]
Output: 1
Example 2:

Input: nums = [4,1,2,1,2]
Output: 4
Example 3:

Input: nums = [1]
Output: 1

Implementation for this problem is required for JavaScript. The boilerplate code can be found in javascript/array/SingleNumber.js

**Comment by Frey0-0** [comment]
I would like to write this code @ShubhKotnala

**Comment by Frey0-0** [comment]
Yeah I would like to do this issue @ShubhKotnala

**Comment by pulkit-singal-28** [comment]
I would like to submit solution to this

**Comment by Frey0-0** [comment]
Raised a PR against this issue @ShubhKotnala.
