### ISSUE TITLE
[JAVA] : FizzBuzz

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#22]
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i (as a string) if none of the above conditions are true.
 

Example 1:
  Input: n = 3
  Output: ["1","2","Fizz"]

Example 2:
  Input: n = 5
  Output: ["1","2","Fizz","4","Buzz"]

Example 3:
  Input: n = 15
  Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]

Implementation for this problem is required in Java. If interested, please find the boilerplate code in `java/array/FizzBuzz.java`

**Comment by rahulch02** [comment]
Hey @ShubhKotnala, I would like to contribute to this.

**Comment by Dnyanesh-Bachhav** [comment]
Hey, I have just added FizzBuzz Solution in java, please check it and consider a merge...
