### ISSUE TITLE
[JavaScript] : FizzBuzz

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#23]
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i (as a string) if none of the above conditions are true.

Example 1:
Input: n = 3
Output: ["1","2","Fizz"]

Example 2:
Input: n = 5
Output: ["1","2","Fizz","4","Buzz"]

Example 3:
Input: n = 15
Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]

Implementation for this problem is required in JavaScript. If interested, please find the boilerplate code in `javascript/array/FizzBuzz.js`

**Comment by christophermorin** [comment]
Hey @ShubhKotnala I'd like to take this one on.

**Comment by ShubhKotnala** [comment]
Hi @christophermorin , please go ahead for this issue and raise a PR whenever you are ready!

**Comment by ShubhKotnala** [comment]
Hi @Kunnu72 , would you like to take a look at #26 ?
If interested, you can go ahead for that issue. 
If not, feel free to look back to the repository, I'll add multiple more problem statements going ahead.
Thanks

**Comment by christophermorin** [comment]
Thanks @ShubhKotnala!
