### ISSUE TITLE
[Python] : FizzBuzz

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#24]
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i (as a string) if none of the above conditions are true.

Example 1:
Input: n = 3
Output: ["1","2","Fizz"]

Example 2:
Input: n = 5
Output: ["1","2","Fizz","4","Buzz"]

Example 3:
Input: n = 15
Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]

Implementation for this problem is required in Python. If interested, please find the boilerplate code in `python/array/FizzBuzz.py`

**Comment by Dnyanesh-Bachhav** [comment]
Hey,can I work on this issue??

**Comment by Dnyanesh-Bachhav** [comment]
Hello @ShubhKotnala  I have added solution to the fizzbuzz problem in python... please check it and can you consider a merge for the same...
