### ISSUE TITLE
[JAVA] : MountainArray

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#25]
Given an array of integers arr, return true if and only if it is a valid mountain array.

Recall that arr is a mountain array if and only if:
arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

Explanation: Following the above constrainsts, 
For an array [1,2,3,3,4,5,4,3,2,1]
    This array is increasing, but not strictly (2, '3', '3', 4) hence the array is not a valid mountain array

For an array [1,2,3,4,5,4,3,2,1]
    This array is strictly increasing, and also strictly descreasing, hence the array is a valid mountain array
 

Example 1:
    Input: arr = [2,1]
    Output: false

Example 2:
    Input: arr = [3,5,5]
    Output: false

Example 3:
    Input: arr = [0,3,2,1]
    Output: true
 
Constraints:
    1 <= arr.length <= 104
    0 <= arr[i] <= 104
 
Implementation for this probelm is required using Java. If interested, please find the boilerplate code in `java/array/MountainArray.java`

**Comment by 035pratheeksha** [comment]
I would love to contribute this issue.Please assign this to me. @ShubhKotnala

**Comment by DevPJ9** [comment]
Hello, @ShubhKotnala I would also like to contribute.

**Comment by Ashpreet-Singh** [comment]
Hey can you assign me

**Comment by ShubhKotnala** [comment]
Hi @035pratheeksha , Assigning issue to you. 
Please go ahead with your contribution and raise a PR whenever you are ready.

**Comment by 035pratheeksha** [comment]
> Hi @035pratheeksha , Assigning issue to you. Please go ahead with your contribution and raise a PR whenever you are ready.

Yup done.Thanks for the opportunity.
I've raised a PR ,please look into that and add me as a contributor for hacktoberfest.

**Comment by ShubhKotnala** [comment]
> Yup done.Thanks for the opportunity. I've raised a PR ,please look into that and add me as a contributor for hacktoberfest.
I can't find your PR. Can you mention PR number here?
Also, please check if the PR has been raised against this repository.

**Comment by 035pratheeksha** [comment]
> > Yup done.Thanks for the opportunity. I've raised a PR ,please look into that and add me as a contributor for hacktoberfest.
> > I can't find your PR. Can you mention PR number here?
> > Also, please check if the PR has been raised against this repository.

Yes.Can you see it now?
Please let me know.

**Comment by 035pratheeksha** [comment]
> > > Yup done.Thanks for the opportunity. I've raised a PR ,please look into that and add me as a contributor for hacktoberfest.
> > > I can't find your PR. Can you mention PR number here?
> > > Also, please check if the PR has been raised against this repository.
> 
> Yes.Can you see it now? Please let me know.

I've now created a new PR....So its PR no. is #49

**Comment by isanketsaha** [comment]
Hi @ShubhKotnala , if this issue is still open. can you assign this to me?

**Comment by ShubhKotnala** [comment]
Sure @isanketsaha

**Comment by isanketsaha** [comment]
Raised PR. Please review. @ShubhKotnala 
PR - #63

**Comment by 035pratheeksha** [comment]
> > > > Yup done.Thanks for the opportunity. I've raised a PR ,please look into that and add me as a contributor for hacktoberfest.
> > > > I can't find your PR. Can you mention PR number here?
> > > > Also, please check if the PR has been raised against this repository.
> > 
> > 
> > Yes.Can you see it now? Please let me know.
> 
> I've now created a new PR....So its PR no. is #49

@ShubhKotnala  ?

**Comment by ShubhKotnala** [comment]
@035pratheeksha , there are some review comments on your PR, I hope you have seen them.
