### ISSUE TITLE
[JavaScript] : MountainArray

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#26]
Given an array of integers arr, return true if and only if it is a valid mountain array.

Recall that arr is a mountain array if and only if:
arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

Explanation: Following the above constrainsts, 
For an array [1,2,3,3,4,5,4,3,2,1]
    This array is increasing, but not strictly (2, '3', '3', 4) hence the array is not a valid mountain array

For an array [1,2,3,4,5,4,3,2,1]
    This array is strictly increasing, and also strictly descreasing, hence the array is a valid mountain array
 

Example 1:
    Input: arr = [2,1]
    Output: false

Example 2:
    Input: arr = [3,5,5]
    Output: false

Example 3:
    Input: arr = [0,3,2,1]
    Output: true
 
Constraints:
    1 <= arr.length <= 104
    0 <= arr[i] <= 104
 
Implementation for this probelm is required using JavaScript. If interested, please find the boilerplate code in `javascript/array/MountainArray.js`

**Comment by nish-ahmd-it** [comment]
Hi @ShubhKotnala  can you assign this task for me please ?

**Comment by Ashpreet-Singh** [comment]
Hey can you assign me this

**Comment by ShubhKotnala** [comment]
Hi @nish-ahmd-it , Assigning issue to you. 
Please go ahead with your contribution and raise a PR whenever you are ready.

**Comment by ShubhKotnala** [comment]
Closing this issue w.r.t. https://github.com/ShubhKotnala/Data_Structures_And_Algorithms/pull/51
