### ISSUE TITLE
[Python] : MountainArray

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#27]
Given an array of integers arr, return true if and only if it is a valid mountain array.

Recall that arr is a mountain array if and only if:
arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

Explanation: Following the above constrainsts, 
For an array [1,2,3,3,4,5,4,3,2,1]
    This array is increasing, but not strictly (2, '3', '3', 4) hence the array is not a valid mountain array

For an array [1,2,3,4,5,4,3,2,1]
    This array is strictly increasing, and also strictly descreasing, hence the array is a valid mountain array
 

Example 1:
    Input: arr = [2,1]
    Output: false

Example 2:
    Input: arr = [3,5,5]
    Output: false

Example 3:
    Input: arr = [0,3,2,1]
    Output: true
 
Constraints:
    1 <= arr.length <= 104
    0 <= arr[i] <= 104
 
Implementation for this probelm is required using Python. If interested, please find the boilerplate code in `python/array/MountainArray.py`

**Comment by Debayan97531** [comment]
Can you please assign it to me??

**Comment by Debayan97531** [comment]
I have added a pr for this code.Will you kindly merge it??

**Comment by Debayan97531** [comment]
#38

**Comment by Debayan97531** [comment]
#39

**Comment by ShubhKotnala** [comment]
Closing w.r.t #39
