### ISSUE TITLE
[JAVA] : Add Searching Algorithms

### ISSUE THREAD

**Issue by ShubhKotnala** [ShubhKotnala/Data_Structures_And_Algorithms#33]
Add Searching Algorithms like binary search, linear search, sentinel search etc.

If interested, please add the algorithms into `java/searching` package

**Comment by Dnyanesh-Bachhav** [comment]
Hey can you assign this issue to me??

**Comment by neharathig** [comment]
Hi, Can you please assign this to me ?

**Comment by neharathig** [comment]
Hi, Can you please assign this to me?

**Comment by Debarpan08** [comment]
!assign

**Comment by deepesh85b** [comment]
Please assign this to me @ShubhKotnala

**Comment by ShubhKotnala** [comment]
Hi @deepesh85b , assigning to you.

**Comment by ArcheR1901** [comment]
Hi @ShubhKotnala please assign me this issue.
